In [1]:
import numpy
n = numpy.arange(27)

In [2]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
n.reshape(3,9)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [5]:
n = n.reshape(3,9)
n

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
import cv2

In [10]:
im_g = cv2.imread("smallgray.png",0)
# this converts the image into a numpy array. The 0 indicates to read it in greyscale.
# 1 would have the image read in rbg colour scales.
im_g
# a grayscale numpy array will be a 2 dimensional array
# in this case it's 3 x 5. Each number represents a pixel in it's specific coordinates.


array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [11]:
im_g_c = cv2.imread("smallgray.png",1)
# A colour numpy array will be a 3 dimensional array which relates to the blue layer, green layer and red layers.
# Each pixel is a mixture of of all three layers
im_g_c
# this array has been transposed. it's the same image as above but each array is now 5 x 3 not 3 x 5. 
# each pixel has a 3 individual colour values. 
# The pixels coordinates depict which value in each array to look at to get the bgr value

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [12]:
# to convert a numpy array to an image we need to use the 
cv2.imwrite("newsmallgray.png", im_g_c)
# we pass in the desired name of the new image and the numpy array we wish to create
# if we get True back then the image should've been created.

True